### ISSUE TITLE
the option `onlyPlugins` need rethinking

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#298]
The option `onlyPlugins` remove a whole category if 1 audit is included. This is no good DX as when debugging I want to see the category scores too. A potential solution could be just remove refs from a category, not the category it self.

blocked by #515 as it includes a helper function to filter refs in a category

**Comment by hanna-skryl** [comment]
Since the issue was created, the filtering logic has been updated and centralized within a single filtering middleware function: #822 and #831.

The current behavior already matches what was requested: categories are kept, and only specific references within them are filtered out based on the `onlyPlugins` and `skipPlugins` options. The middleware uses the `filterItemRefsBy` helper function (introduced in #515) to filter references within a category, ensuring that categories remain intact while filtering only the relevant plugin references, providing the expected developer experience.
