### ISSUE TITLE
Lighthouse plugin sometimes needs to be re-run

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/cli#624]
Code PushUp failed in GitHub Actions because of Lighthouse plugin - solved by re-running job.

[`Runtime error encountered: Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_NAVSTART)`](https://github.com/code-pushup/cli/actions/runs/8661766002/job/23752375211#step:5:34)

**Comment by BioPhoton** [comment]
This was due to timeout issues which are wildly different from the error messages.

I document the different errors caused by timeout here:
https://github.com/code-pushup/cli/blob/main/packages/plugin-lighthouse/CONTRIBUTING.md#troubleshooting

I would close this one as the CI job is quite stable now compared to Bach then. 
 
@matejchalk if u agree let’s close it.

**Comment by matejchalk** [comment]
Yes, I haven't seen this error for some time. It's all been `Unable to connect to Chrome` errors recently, but that's tracked by #538. Closing this one.
