### ISSUE TITLE
Error: The following category references need to point to an audit or group: eslint#formatting (group)

### ISSUE THREAD

**Issue by m00k** [code-pushup/cli#682]
### What happened?

Following [this example configuration](https://github.com/code-pushup/cli/blob/main/packages/plugin-eslint/README.md?plain=1#L176) for the **ESLint plugin** I run into:

```bash
The following category references need to point to an audit or group: eslint#formatting (group)
```

### What steps did you take?

see above

### Code PushUp package version

v0.44.1

### What operation system are you on?

Linux

### Node version

18.19.0

**Comment by m00k** [comment]
the `groups` output by `listAuditsAndGroups()`
in [packages/plugin-eslint/src/lib/meta/index.ts](https://github.com/code-pushup/cli/blob/v0.44.1/packages/plugin-eslint/src/lib/meta/index.ts) do not contain a slug `formatting`: 

```json
[
    {
        "slug": "problems",
        "title": "Problems",
        "description": "Code that either will cause an error or may cause confusing behavior. Developers should consider this a high priority to resolve.",
        "refs": [
           //...
        ]
    },
    {
        "slug": "suggestions",
        "title": "Suggestions",
        "description": "Something that could be done in a better way but no errors will occur if the code isn't changed.",
        "refs": [
           //...
        ]
    },
    {
        "slug": "react-best-practices",
        "title": "Best Practices (react)",
        "refs": [
           //...
        ]
    },
    {
        "slug": "react-possible-errors",
        "title": "Possible Errors (react)",
        "refs": [ 
           //...
        ]
    }
]
```

**Comment by matejchalk** [comment]
The slug `formatting` is correct, it is defined here: https://github.com/code-pushup/cli/blob/v0.44.1/packages/plugin-eslint/src/lib/meta/groups.ts#L10-L29

These pre-defined groups are created on-the-fly from the ESLint rules which are turned on in your configuration. The Formatting group references all rules with `meta.type` equal to `'layout'`. However, since groups without any references would be invalid (nothing to base score calculation on), this group will be creates if no `layout` rules are present in your configuration.

So I suspect that's why you get the error, your ESLint config doesn't contain any `layout` rules (they're actually quite rare in practice, the `problem` or `suggestion` types seem to be much more common). In which case simply removing that group reference from the category should fix the problem.

(BTW, if you want to know which groups are created, then the `print-config` outputs the resolved configuration as JSON.)

**Comment by m00k** [comment]
i see. thanks for the explainer!
